/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CodeImport } from './routes/code'

// Create/Update Routes

const CodeRoute = CodeImport.update({
  path: '/code',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/code': typeof CodeRoute
}

export interface FileRoutesByTo {
  '/code': typeof CodeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/code': typeof CodeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/code'
  fileRoutesByTo: FileRoutesByTo
  to: '/code'
  id: '__root__' | '/code'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CodeRoute: typeof CodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  CodeRoute: CodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/code"
      ]
    },
    "/code": {
      "filePath": "code.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
