/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CodeIndexImport } from './routes/code/index'
import { Route as CodeTokenImport } from './routes/code/$token'

// Create/Update Routes

const CodeIndexRoute = CodeIndexImport.update({
  path: '/code/',
  getParentRoute: () => rootRoute,
} as any)

const CodeTokenRoute = CodeTokenImport.update({
  path: '/code/$token',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/code/$token': {
      id: '/code/$token'
      path: '/code/$token'
      fullPath: '/code/$token'
      preLoaderRoute: typeof CodeTokenImport
      parentRoute: typeof rootRoute
    }
    '/code/': {
      id: '/code/'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/code/$token': typeof CodeTokenRoute
  '/code': typeof CodeIndexRoute
}

export interface FileRoutesByTo {
  '/code/$token': typeof CodeTokenRoute
  '/code': typeof CodeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/code/$token': typeof CodeTokenRoute
  '/code/': typeof CodeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/code/$token' | '/code'
  fileRoutesByTo: FileRoutesByTo
  to: '/code/$token' | '/code'
  id: '__root__' | '/code/$token' | '/code/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CodeTokenRoute: typeof CodeTokenRoute
  CodeIndexRoute: typeof CodeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  CodeTokenRoute: CodeTokenRoute,
  CodeIndexRoute: CodeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/code/$token",
        "/code/"
      ]
    },
    "/code/$token": {
      "filePath": "code/$token.tsx"
    },
    "/code/": {
      "filePath": "code/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
